# Exercise: Using `numpy` to work with matrices & implement base exchanges
<font color='blue'><b>Goal:</b></font>
Computing simplex tableaus using `numpy`.

<font color='blue'><b>Required packages:</b></font>`numpy`

Consider the following LP, given in canonical form.
\begin{equation*}
\begin{array}{lrcrcrcr}
\max & - x_1 & - & x_2 \\
&  & - & x_2 & \le & -1 \\
& -x_1 & - & x_2 & \le & -2 \\
& -4 x_1 & + & x_2 & \le & -2 \\
& -x_1 & + & x_2 & \le & 1 \\
& x_1 & & & \ge & 0 \\
& & & x_2 & \ge & 0 \\
\end{array}
\end{equation*}

By adding slack variables we obtain the equivalent standard form shown below.
\begin{equation*}
\begin{array}{lcccccrcrcl}
\max &       &     &      &      & -  &  x_1 & - & x_2 &   &    \\
     &   y_1 &     &      &      &    &      & - & x_2 & = & -1 \\
     &       & y_2 &      &      & -  &  x_1 & - & x_2 & = & -2 \\
     &       &     & y_3  &      & -  & 4x_1 & + & x_2 & = & -2 \\
     &       &     &      & y_4  & -  &  x_1 & + & x_2 & = &  \phantom{-}1 \\
     &       &     &      &      &    &      &   & x   & \in  &  \mathbb{R}^2_{\geq 0} \\[0.2em]
     &       &     &      &      &    &      &   & y   & \in  &  \mathbb{R}^4_{\geq 0}\\
\end{array}
\end{equation*}

Let us choose the slack variables $y$ as a basis. We then obtain the simplex tableau
\begin{equation*}
\qquad \begin{array}{l|rrrrrr|r}
& y_{1} & y_{2} & y_{3} & y_{4} & x_{1} & x_{2} &  \\
\hline
& 1 & 0 & 0 & 0 &  0 & -1 & -1 \\
& 0 & 1 & 0 & 0 & -1 & -1 & -2 \\
& 0 & 0 & 1 & 0 & -4 &  1 & -2 \\
& 0 & 0 & 0 & 1 & -1 &  1 & 1
\end{array}
\end{equation*}
with basic solution 
$(y_1,y_2,y_3,y_4,x_1,x_2)=\left(-1,-2,-2,1,0,0\right)$.

**How can we switch from one basis to another without applying multiple exchange steps?** To answer this question, it is convenient to use matrix multiplication. In python, we can use the package `numpy` for dealing with matrices.

## Introduction to `numpy`
`numpy` (short for numeric python) allows for a diverse range of scientific computations. For us, however, it will be a tool to compute matrix multiplications.

### Feeding a matrix to `numpy`
The following code shows how to store the matrix
$$A:=\begin{bmatrix}1&3\\4&5\end{bmatrix}$$
in `numpy`: as a list of lists which correspond to the row vectors of $A$.

In [1]:
# Import the package
import numpy as np

A = np.matrix([
    [1,3],
    [4,5]
])

A

matrix([[1, 3],
        [4, 5]])

### Matrix multiplication
Consider $B:=\begin{bmatrix}1&5&4\\6&9&0\end{bmatrix}$. Then $A\cdot B$ is computed in `numpy` via the `matmul` function:

In [2]:
B = np.matrix([
    [1,5,4],
    [6,9,0]
])

np.matmul(A,B)

matrix([[19, 32,  4],
        [34, 65, 16]])

### Matrix transposes
To calculate $A^T$, use the `np.transpose` function:

In [3]:
np.transpose(A)

matrix([[1, 4],
        [3, 5]])

### Working with matrix inverses
The inverse $A^{-1}$ of $A$ can be calculated using `linalg.inv`:

In [4]:
np.linalg.inv(A)

matrix([[-0.71428571,  0.42857143],
        [ 0.57142857, -0.14285714]])

**Note, however, that explicitly computing inverses can lead to numerical stabilty issues.** We will thus try to avoid it whenever possible. One example is when we want to solve a system of the form $Ax = B$, where the solution is $x = A^{-1}B$, given that $A$ is invertible (note that with $A$ and $B$ as given above, the solution $x$ is a matrix). Such systems can be solved using the `linalg.solve` function:

In [5]:
# using linalg.solve
print(np.linalg.solve(A,B))
print()

# unstable way using linalg.inv and matrix multiplication
print(np.matmul(np.linalg.inv(A),B))

[[ 1.85714286  0.28571429 -2.85714286]
 [-0.28571429  1.57142857  2.28571429]]

[[ 1.85714286  0.28571429 -2.85714286]
 [-0.28571429  1.57142857  2.28571429]]


In the above example you don't see a difference because the matrix $A$ is not ill-conditioned, but be advised that both in terms of stability and in terms of running time, using `linalg.solve` is the preferred way to do it.

## Base exchange with `numpy`
Use `numpy` to write a function, which, given a tableau $T$ and a vector $v$ of column indices corresponding to a basis, returns a new tableau $T'$ with respect to $B$.

In [ ]:
def tableau(T,v):
    # IMPLEMENT YOUR FUNCTION HERE
    
    return T_prime

## Testing your implementation
Feed the above tableau in your function, with $v=[5,4,2,3]$ and check whether you obtain the following tableau:
\begin{equation*}
\begin{array}{l|rrrrrr|r}
& y_{1} & y_{2} & y_{3} & y_{4} & x_{1} & x_{2} &  \\
\hline
& -1 &  0 & 0 & 0 & 0 & 1 & 1 \\
&  1 & -1 & 0 & 0 & 1 & 0 & 1 \\
&  5 & -4 & 1 & 0 & 0 & 0 & 1 \\
&  2 & -1 & 0 & 1 & 0 & 0 & 1
\end{array}
\end{equation*}

In [ ]:
# TEST YOUR IMPLEMENTATION HERE